name: Deploy to GitHub Pages

on:
  push:
    branches: ["master", "main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build Core
        run: |
          cd core
          npm install
          npm run build

      - name: Build Web
        run: |
          cd web
          npm install
          npm run build

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './web/dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
